recodehive/awesome-github-profiles

styles.css
fixes #149 
This Pull Request addresses the issue where the "Recode Hive" text in the navigation bar on `blog.html` becomes invisible when dark mode is activated. The text lacks sufficient contrast against the dark background, making it unreadable.
- Updated CSS to enhance text visibility in dark mode.
=> Fix "Recode Hive" Text Visibility in Dark Mode on Blog

githubbadge.html
- Made the tables responsive so that the badges appear clear & it's info as well on mobile view.
https://github.com/user-attachments/assets/5fff4f9c-5ef3-470a-97b2-bb3767fb1c4f
_@sanjay-kv sir please review & merge this pr under GSSoC'24_
=> Made the tables responsive of github-badges page.

pages/githubbadge.html
- Fixed the badges icon colour for dark & light mode of github badges page.
- Now, these icons will look black in light mode & white in dark mode.
@sanjay-kv sir please review & merge this pr under GSSoC'24
=> Fixed the badges icon colour for dark & light mode

pages/githubbadge.html, styles/blog.css, styles/styles.css
- Made the blog page & github badges page responsive for mobile view.
- Removed the extra blank space from the right side of the web pages.
https://github.com/user-attachments/assets/2fb7a82f-557a-4fe0-ac44-a5942e903dd1
@sanjay-kv sir please review & merge my pr under GSSoC'24
=> Made the blog page & github badges page responsive

styles/styles.css
- Fixed filter box style for dark mode.
- Now, the filter options will be clearly visible in both light mode & dark mode.
https://github.com/user-attachments/assets/fb6ca6a4-86e5-43a6-824b-5bb834c5bd39
@sanjay-kv @dinxsh please review & merge my pull-request under GSSoC'24
=> Fixed filter box style for dark mode

styles/styles.css
closes #302 
This PR addresses the issue where the text "No profile found" is not visible in light mode due to low contrast between the text color and the background color. Users with light mode enabled could not see the text, leading to a poor user experience.
=> Fix Text Visibility in Light Mode

styles/styles.css
Fix issue : #548 
Changes Made:
-Increased the margin on the right side of the content to ensure the social icons no longer overlap with the text.
-Ensured that this change is responsive, so the layout works correctly across all screen sizes.
=> Fix issue with overlapping social icons on gh-pages

pages/githubbadge.html, styles/githubbadge.css
This pull request addresses an issue with the font color of the subheading on the GitHub badge page, ensuring that it is suitable for the light theme. The previous font color was not legible, and this change improves readability and enhances the user experience for those using the light theme.
=> fixed subheading font color for light theme on gh-pages

README.md
Fixes #592 
Add step 6:stage your changes under the 'Contribute' heading of README.md
=> Add a Step in README.md to stage your changes (under "Contribute" Subheading)

index.html
Now when the github icon is clicked, user gets redirected to this repository
@dinxsh kindly add the labels [gssoc-ext](https://github.com/recodehive/awesome-github-profiles/labels/gssoc-ext) , [hacktoberfest-accepted](https://github.com/recodehive/awesome-github-profiles/labels/hacktoberfest-accepted) , [level1](https://github.com/recodehive/awesome-github-profiles/labels/level1) / [level2](https://github.com/recodehive/awesome-github-profiles/labels/level2) / [level3](https://github.com/recodehive/awesome-github-profiles/labels/level3)
=> bugfix: add correct github url

index.html, styles/styles.css
Issue #634 . [SOLVED]
https://github.com/user-attachments/assets/7bae9f49-9226-4052-971a-247b71571e3f
This will enhance the scalability and usability of the website while eliminating any ambiguity for the users.
=> Updated X[Twitter] logo.

README.md
This pull request addresses the inconsistency in the naming of the repository throughout the project documentation. In some places, the repository was referred to as "Awesome GitHub Profiles" instead of  "Awesome-Github-Profiles" such as 
1.  
2.
3.
Changes Made:
Standardized all references to "Awesome-Github-Profiles" for consistency, particularly in the README.md file.
Please review and let me know if further adjustments are needed. Thanks!
Closes #604
=> Fixed naming inconsistency in repository references

CONTRIBUTING.md, README.md
This PR corrects the readme on the `main` branch by making users switch to the working branch `gh-pages` branch before creating a new branch to add the feature, this is to ease the process of adding a new feature for beginners who don't understand the ins and outs of git on the CLI, addressing issue #683. Now I've created the CONTRIBUTING.md file to be put into the `main` branch as well as linked to it on the readme page using a hyperlink.
=> [fix] correct readme on main branch for easier instructions, create CONTRIBUTING.md file

CONTRIBUTING.md, README.md
As previously mentioned in issue #705, the readme on the `gh-pages` branch links to an invalid link, since there is no CONTRIBUTING.md file, and even the link is not linking correctly to a file according to the Github syntax `./CONTRIBUTING.md`
The old text in the README.md
``` MD
Contributions are always welcome!
Please read the [contribution guidelines](contributing.md) first.
```
The solution: 
```MD
Contributions are always welcome!
Please read the [Contribution Guidelines](./CONTRIBUTING.md) first.
```
=> [fix] add CONTRIBUTING.md file to the gh-pages branch, correct invalid hyperlink

styles/modal.css, styles/styles.css
Error: Profile Addition PopUp Closing Icon Not Showing in Dark Mode
Fixes :
1. Closing icon is there but is not visible because of its color.
2. Also text is not showing.
3. Also modal is not closing
4. Button's color on hover also not matched (changed to same as modal color)
https://github.com/user-attachments/assets/7030af3c-7d75-4502-a2d0-2cc1702cb219
=> Fixes in Modal | Issue #775

styles/styles.css
Completed #810 
https://github.com/user-attachments/assets/ce31b209-dbc1-40eb-8000-5b4af701731c
=> Fix Footer | Issue #810

index.html
PR Description:
This PR addresses the removal of the "Add Profile" button from the navbar, as mentioned in Issue #910. The button has been removed from all pages to comply with the maintainer's request. No other sections or functionalities have been affected.
Removed "Add Profile" from the navigation bar across all pages.
Tested the navigation flow to ensure all buttons function correctly after this change.
Please review the changes and let me know if further adjustments are needed. 
If I have made any mistakes, please let me know, as I am still learning.
Screenshots after changes -
=> Remove "Add Profile" Button from NavBar (Issue #910)

pages/githubbadge.html
I have added the video tutorial link in the quickdraw section and modified the statement about it.
https://github.com/user-attachments/assets/45a71495-b931-4e6e-a2e7-77d9bc7c076f
This PR closes ISSUE #912 
@sanjay-kv @HimangshuSharma01
=> Fixed quickdraw section and added video tutorial link || ISSUE #912

scripts/retriveprofile.js
https://github.com/user-attachments/assets/41eb5722-2290-41b5-a0a3-268bdfe09925
This pull request reduced the number of profiles displayed on a single page. Now, the profiles are limited to 18 per page, and users can navigate between pages using the provided "Previous" and "Next" buttons.
This pull request **closes issue #905**.
- `hacktoberfest-accepted`
- `GSSOC-EXT`
- `level1`
=> Reduce number of visible profiles on the page

styles/styles.css
=> Add Gradient to the progress bar 

index.html, styles/styles.css
Fixes: #951 
- Changes made in dark mode 
1) placeholder text better visibility
- Footer changes
1) properly aligned content in footer of all pages
2) better visibility in dark mode
=> dark mode enhancement - placeholder text and footer

.vscode/settings.json, index.html, pages/blog.html, pages/compare.html, pages/construction.html, pages/events.html, pages/exploremore.html, pages/faq.html, pages/githubbadge.html, pages/help.html, pages/saved-blogs.html
This PR closes issue #757, the commits I've made remove the redundant parts in the Navigation Menu (both for PC and Mobile for responsiveness) where sections `Learn` and `Blog` Link to the **same** [blog.html](https://github.com/recodehive/awesome-github-profiles/blob/gh-pages/pages/blog.html) page at the **same time**, and in the cases where a page contains only one section Named `Learn` it is now renamed to `Blog` to maintain consistency across all webpages.
=> [fix] remove redundant sections containing both `Learn` and `Blog` sections, and rename standalone `Learn` sections to `Blog` 

pages/blog.html, pages/events.html
This PR closes issue #1069, adding the `Login` Section to the Navigation Menu both for PC and Mobile versions of the website on the `Events` and `Blogs` Pages of the website, this is to maintain consistency with the rest of the Pages on the website that all have these features.
=> [fix] add Login Section and Dark Mode Button on Events and Blogs Pages
