index.html
Need Dark Mode for this Theme: #11
=> Need Dark Mode for this Theme: #11

index.html
=> Change the add you repo to middle before search button

dark-mode.js, index.html, retriveprofile.js, styles.css
Created Seperate Html Css Js Files .
=>  Create Seperate html css and js files #22

.github/workflows/autocomment-iss-close.yml, .github/workflows/close-old-issue.yml, .github/workflows/close-old-pr.yml
=> added multiple workflows

dark-mode.js, index.html, retriveprofile.js, styles.css
fixes #32 
This pull request introduces sun and moon icons to the dark mode toggle switch, aiming to enhance user experience by providing clear visual cues for theme switching. The sun icon represents daylight mode, while the moon icon signifies nighttime mode.
https://github.com/user-attachments/assets/eed2fe80-030f-401c-9882-045331da43dc
=> Add sun and moon icons to dark mode toggle for improved UI

.all-contributorsrc
- I have resolved the merge conflict issue of .all-contributorsrc file.
- Now, all the contributors are stored in different objects.
@sanjay-kv sir please review & merge this pull-request under GSSoC'24
=> Resolved the merge conflict issue of .all-contributorsrc file

retriveprofile.js, styles.css
https://github.com/user-attachments/assets/ef59392f-3536-48ef-b3de-427851e347db
=> Want to make scrollable profile image where #30

retriveprofile.js, styles.css
hey @sanjay-kv @dinxsh please merge it without any labels.
i Forgot to Handle the case where image height will be different so fixed that
https://github.com/user-attachments/assets/f27a008c-eab0-4d73-8286-62159895d3fb
=> image was scrolling till half only before fixed that

styles.css
I have added the hovering effect on the options 
closes : #31 
https://github.com/user-attachments/assets/a1668948-96cd-4de1-ab7c-86a9163aa854
https://github.com/user-attachments/assets/c8bf147d-bcea-4263-8b9f-ac6d5889aaa2
=> Added Hovering Effect to the Options 

styles.css
I have fixed the responsiveness of the footer section
=> Fixed responsiveness Of the footer sections 

index.html
=> Need to change the text on footer #82

index.html, styles.css
I have added the  side icons of social media 
@sanjay-kv sir i know you assigned this to asymtode but i already started working on it as you raised the issue as i commented already so  i thought you will give me chance So please review it i will leave the events page issue for @Asymtode712 
@Asymtode712 Bro hope you also understand i already did 70% of work that's why i raised this pr you can do events page i have no issues with that
https://github.com/user-attachments/assets/0b79097d-5763-407d-80f9-d47c5f08282f
closes : #84
=> Added Side icons of Social media 

index.html, styles.css
Part of #84  & Extension to #92 
- Changed the side icons position to the right side
- Added hovering effects for icons with theme compatibility
https://github.com/user-attachments/assets/6463d9d4-d155-4c94-b48c-0cdc60872897
=> adjusted positioning and added hovering effects

githubbadge.html, index.html, styles.css
I have created a seperate page Guthub-Badge 
https://github.com/user-attachments/assets/08cc1eac-bec7-4323-827f-103f94b2ff2a
closes : #78
=> Created seperate page Github-Badge 

styles.css
=> Changed color of footer

events.html, explore.css, exploremore.html, githubbadge.html, index.html
I have added the explore more page 
https://github.com/user-attachments/assets/50044fe0-1909-40d4-b468-f7e18b1ed6e7
closes : #86
=> Added Explore More Page 

events.html, exploremore.html, githubbadge.html, index.html, styles.css
I have added the route to home when clicking on logo 
https://github.com/user-attachments/assets/c6e76d4f-0944-4ab0-94fc-347703485528
closes : #101
=> Added Link for home when clicking on logo

events.html
I have added the details of the events
closes : #106
=> Added Events 

index.html, styles.css
fixes #114 
This pull request introduces enhanced social media icons featuring a stylish hover animation and improved support for dark mode.
Changes
Hover Animation: Added a visually engaging hover effect where the background color animates from the bottom up, and the icon color changes to white upon hover. This improves user interaction and visual appeal.
https://github.com/user-attachments/assets/f9434c9f-a0a7-488f-a73e-8ba0f5cedcd1
=> Enhance Social Media Icons with Hover Animation

index.html, retriveprofile.js
I have added the no profile found text when no profile found for the search query 
https://github.com/user-attachments/assets/2a0aa6e6-ef13-464f-bd96-153d58b7458d
closes : #118
=> Added No Profile Found

events.html, exploremore.html, githubbadge.html, index.html
I have added the tools in the navbar 
closes : #108
=> Added Tools In the Navbar 

blog.css, blog.html, blog.js, blog.json, index.html
Closes  #79
https://github.com/user-attachments/assets/f9938d32-4b45-440e-9c09-d8ce4b2a06b1
=> Add the blog page details #79

index.html, styles.css
Enhanced the Search bar sir i have enhanced the search bar by adding an opening animation and a closing animation 
And Removed the outline of blue color 
https://github.com/user-attachments/assets/dd3a3047-1da4-4466-8335-0d332f7e9144
closes : #126
=> Search bar

styles.css
Hey @sanjay-kv 
issue closes #122 
I have Styled the Default Vertical Scrollbar of the Website to Custom One.
- It **follows the Website's theme** 
- **It Works Both in "Light-Mode" and "Dark-Mode"** following respective themes.
- **Added "Rocket" Buttons to the Scrollbar** to Up-Down the Scrollbar manually.
**Light Mode -**
**Dark Mode -** 
Please take a look and review it.
Thankyou!
=> ✔️ Styled the Vertical Scrollbar of Website

index.html, retriveprofile.js, styles.css
closes #58 
https://github.com/user-attachments/assets/01406188-8186-45e5-a343-9fb714d69142
hey @sanjay-kv sir please add your firebase config files 
here in retriveprofile.js and make sure database rules are public :
=> Feature: Want to Add View Count in each Profile #58

index.html, retriveprofile.js, styles.css
I have added the sort feature where the profiles will be sorted on the basis of views 
closes : #148 
https://github.com/user-attachments/assets/7165dde7-a1a5-4fd6-a555-f5655e5e5093
=> Added sort feature on the basis of views 

blog.css, blog.html, githubbadge.css, githubbadge.html
I have created these sections and added to below the blogs and github badge sections
Sir please check and let e know if i did any mistake
https://github.com/user-attachments/assets/cda3d0a6-236b-449f-a8cf-6816f7dee532
https://github.com/user-attachments/assets/17132eb5-5429-4f16-b4fb-7aeefe0a0174
closes : #164
=> Added Learn github from scratch sections in Blogs and Github Badge Page 

pages/blog.html, pages/events.html, pages/exploremore.html, pages/githubbadge.html
Fixes #177 
- Ensured constant order of navlinks across all pages of our website
- Fixed some navlinks
https://github.com/user-attachments/assets/0ac5d440-497f-4487-88eb-99cbd031d008
=> fixed navlinks across all pages

styles/styles.css
fixes  #154 
This pull request updates the button styles on the website to better align with the current theme and enhance user experience. The changes include color adjustments, styling improvements, and ensuring consistency across light and dark modes.
=> Enhance Button Styles to Match Current Theme and Improve UX

index.html, pages/blog.html, pages/events.html, pages/exploremore.html, pages/githubbadge.html, pages/help.html
fixes #159 
Changed the name blog to learn in navbar
=> Changed the name blog to learn in navbar

index.html, pages/blog.html, pages/events.html, pages/exploremore.html, pages/githubbadge.html, scripts/hamburger.js, styles/hamburger.css
Hey @sanjay-kv 
issue closes #120 
I have made the Hamburger menu for the website to all the existing pages.
- The **hamburger menu is responsive** for all screensizes 
- **Added Smooth Transitional effects** to open the nav-menu of hamburger
- **Added Animation to the "Hamburger logo"** to make it interactive onclicking.
**Before Click :** 
**After Click :(animated)**
- **Created separate .css and .js files** for the hamburger, so that in future it will be easier to add this hamburger into newly created Pages!
Please take a look - 
https://github.com/user-attachments/assets/08ddd491-be79-4c7c-bb85-af362dd3f1e6
Thankyou!
=> ✔️Implemented "Hamburger menu" and Made it Responsive !

scripts/retriveprofile.js, styles/styles.css
I have added the likes feature 
https://github.com/user-attachments/assets/1d19f6a5-c1cd-476c-8bbc-4cdaa6585985
closes : #147
=> Added Likes Feature 

index.html, pages/blog.html, pages/events.html, pages/exploremore.html, pages/githubbadge.html, pages/help.html
Fixes #195, #207 
- Removed duplicates from the navbar
- Added link to `Add Profile` button
- Removed additional add profile button from the landing page
https://github.com/user-attachments/assets/12fdd949-3041-453a-a712-9acaa913283c
@sanjay-kv Please check and merge this PR
=> removed duplicates and added links

pages/events.html
Closes #156
https://github.com/user-attachments/assets/1f271b02-1fc8-4a17-80f9-93b84ecf687c
=> Error: Event page not appearing as expected. #156

index.html, pages/blog.html, pages/compare.html, pages/exploremore.html, pages/help.html, scripts/compare.js, styles/compare.css
I have added a page for comparison between two profiles
closes : #125 
https://github.com/user-attachments/assets/e07f4ade-7559-4ddf-8b53-9bdc28c4f36e
=> Added Compare Profile page from scratch

index.html, pages/blog.html, pages/compare.html, pages/events.html, pages/exploremore.html, pages/githubbadge.html, pages/help.html, styles/hamburger.css
closes: #245 
made Navbar Consistent across all pages
=> Nav bar is not consistent across on the pages. #245

styles/blog.css, styles/githubbadge.css
=> Stretched view on learn page and github badge page #244

styles/blog.css
@sanjay-kv I have fixed the popup. I have removed the scrollbar which was not needed.
Closes #229 
I have also fixed the responsive design of the popup. 
which was previously overflowing 
Now, fixed to this 
Scroll is also removed.
=> Popup Fixed

styles/blog.css
Reverts recodehive/awesome-github-profiles#251
=> Revert "Popup Fixed"

scripts/compare.js
closes #241 
Written More Optimized Code as before all the contributor details was getting fetched first then it was getting compared.
which is fine with small no. but when these no. of profile becomes big it will cause problems
---
https://github.com/user-attachments/assets/40f01b3e-36b4-4949-9531-919a05769983
---
---
https://github.com/user-attachments/assets/7a525b19-71af-45c5-a1e3-95d0b460ba1a
---
=> Compare Feature not working #241

pages/blog.html, pages/compare.html, pages/events.html, pages/exploremore.html, pages/githubbadge.html, pages/help.html, styles/events.css
I have fixed the navlinks issue not it will properly Route to correct path 
closes : #255
=> Fixed Nav Links Issue

pages/events.html, styles/events.css
I have added the working timeline for that 
And pushed the exact video links 
closes : #246 
https://github.com/user-attachments/assets/801caf72-6e7b-4e94-a379-e5278618f97e
=> Added Working timeline for the events page and fixed the video links  in the Events page 

pages/githubbadge.html, styles/styles.css
Closes #230 
I have changed all the heading color to white in github badges page when in dark mode.
=> visibility fixed in github badge

scripts/retriveprofile.js
I have added a validation on the views so that only 1 view per browser will be counted 
https://github.com/user-attachments/assets/8f947ba6-5fd1-4d91-8c9e-340ac5e69d04
closes : #219
=> Added Validation on views to count One view per browser

pages/blog.html, pages/saved-blogs.html, scripts/blog.js, scripts/retriveprofile.js, styles/blog.css
I have added a saved blog functionality where user can save the blog and can read that later 
https://github.com/user-attachments/assets/fa293f96-25d4-46e4-8f44-63d80d32e21c
closes : #231
=> Added Saved Blog Functionality 

pages/blog.html, pages/githubbadge.html
I have added a tilt effect to the image s
https://github.com/user-attachments/assets/031c7709-ac2f-46c4-aa03-048eb69bdd9d
closes : #232
=> Added Tilt Effect to the images

index.html, scripts/retriveprofile.js
Fixes #223 
- Implemented sorting functionality for profiles based on like count
- Added like count display beneath each sorted profile
- Updated Firebase integration to fetch and update `likes` data in real-time
https://github.com/user-attachments/assets/c79b8288-c7c8-45a0-a1ce-560598dbe7e6
=> Added profile filtering based on likes

styles/blog.css
Closes #271 
I have removed the extra spacing and aligned the cards to center 
Also, I have made the save blog button to color white in dark mode
=> Spacing fixed in blogs

index.html, scripts/revealelementsonscroll.js
#213 
https://github.com/user-attachments/assets/3ca2bd25-6994-4993-a1fd-9c936c4e4c01
=> Feature: Added Reveal elements on scroll

index.html, pages/blog.html, scripts/blog.js, scripts/retriveprofile.js, styles/blog.css, styles/styles.css
I have created a toast notification for showing the events happened 
https://github.com/user-attachments/assets/f918648a-772e-4e43-9564-1a9c40dfcd7b
closes : #259
=> Created Toast Notification 

scripts/retriveprofile.js
I have fixed the design of the profile card as it is changing the designing on selecting the filter 
closes : #278 
https://github.com/user-attachments/assets/0739a4e8-d074-46bd-bc92-af35ed31bdaf
=> FIxed profile card changing design when Adding filter options

styles/styles.css
https://github.com/user-attachments/assets/7730b6df-727e-40b5-91a9-02f5a61f26c0
I have applied this color @sanjay-kv sir please check and let me know if want different color
=> Fixes color of toast 

styles/styles.css
I have added a cursor pointer to the Toggle Switch 
https://github.com/user-attachments/assets/120a3e61-6fee-413d-a8e5-38588a5928da
closes : #277
=> Added cursor pointer to the Toggle switch icon 

scripts/blog.js
I have added a feature to unsave the blog 
closes :  #275 
https://github.com/user-attachments/assets/080c24e3-382a-40db-93ee-dd262042bbc4
=> Added a Feature to unsave the blog 

index.html, scripts/retriveprofile.js
I have fixed the filtering for those selections now these are working correctly 
closes : #295 
https://github.com/user-attachments/assets/a3981836-8d7e-4f43-912b-50e41516668f
=> Fixed least Likes and Most Likes Filtering 

styles/help.css
Fixes: #298
- Made the help page responsive.
- Now the help page will look responsive in mobile-view as well.
https://github.com/user-attachments/assets/a8a698f8-a7bb-49cd-9c72-b51050ed2e10
@sanjay-kv sir please review & merge this PR under GSSoC'24
=> Made the help page responsive.

pages/events.html, styles/events.css
@sanjay-kv I have fixed the animation for events timeline.
I have removed the blue boxes.
=> Events timeline animation fixed

pages/help.html
- Made the Hamburger Button of navbar functional.
- Now, the navbar will be fully-functional.
https://github.com/user-attachments/assets/b015654a-39c7-416a-ab26-b72e1e0bdade
@sanjay-kv sir please review & merge this PR under GSSoC'24
=> Made the Hamburger Button of navbar functional on Help page.

pages/exploremore.html
- Removed duplicate links from navbar of exploremore page.
- Also, added Add profile link because it was not redirecting earlier.
@sanjay-kv sir please review & merge this PR under GSSoC'24
=> Removed duplicate links from navbar of exploremore page.

.all-contributorsrc
Closed #322 
Added Vaibhav-kesarwani
=> Added Vaibhav-kesarwani

index.html, pages/blog.html, pages/compare.html, pages/events.html, pages/exploremore.html, pages/githubbadge.html, pages/help.html, pages/saved-blogs.html
Hey @sanjay-kv 
- issue closes #456 
I have added dynamic date functionality to the copyright section to update yearly
=> AddedAdd dynamic date functionlity to the copyright section to update yearly

index.html, scripts/retriveprofile.js, styles/pagination.css
- Adds logic for pagination in the retriveprofile.js file
- Creates buttons for Previous and Next page
- Also, styles these buttons
=> Add pagination 

styles/styles.css
**Description**
This PR adds a sticky navbar to improve navigation on the website.
Closes: #532 
https://github.com/user-attachments/assets/ca879bdb-96fb-44d7-8593-37b26e1e97c1
=> Added Sticky Navbar Feature

README.md
=> updated the email address of the admin in readme file.

index.html, pages/blog.html
Fixes #589 
When user clicks on twitter icon, it points to the correct profile
=> Fix: correct twitter url

pages/blog.html
fixes the issue #587 which fixed typos and paraphrased the footer content
=> fix typo and paraphrase footer content

README.md
I have removed my copy images, there is only one original image and I have added my GitHub link to it.
=> remove my duplicate image

pages/githubbadge.html, styles/styles.css
fixes #622 
https://github.com/user-attachments/assets/23cfd7e6-d6f4-4bda-b806-feb9f71b2ba4
=> Removed Blank Space 

README.md
This PR adds my GitHub profile to the repository as part of my contributions under GSSoC 2024 ext and Hacktoberfest.
=> Added Rugved's GitHub profile

scripts/ScrollToTop.js
Hi @sanjay-kv 
issue number: #595 
I have fixed the scroll issue which previously was jumping to the top.
now it is  smoothly scrolling.
[recording.webm](https://github.com/user-attachments/assets/a412e130-4926-4b2f-963b-4ce92382eb67)
Apart from this you also assign me #616 issue but there was merge conflict , now i got that why that was happening.
It was silly mistake from my side.
Can you please open that issue?
Now , I can solve that within short time
=> scroll to top jump fixed by smooth scroll

styles/blog.css
=> overlay over navbar fixed

pages/githubbadge.html
Add the text and link to be page as mentioned in the issue
=> Added the text and link

pages/githubbadge.html
=> achievement startStruck

pages/events.html, styles/events.css
Fix: #682
- Aligned the scroll element properly.
- Fixed  the leaking of animation near footer.
- Corrected overlap of pseudo elements with navbar by properly adjusting z-index.
https://github.com/user-attachments/assets/c7bacc07-d401-42fc-9c7b-f8ba864a11e2
=> Fix: #682 Corrected events scroll element

login.css, login.html
-the show password toggle added
-you can show and hide password now
https://github.com/user-attachments/assets/a5bd8065-3a03-4a3d-a9dd-746df01ad13b
=> show password feature added

package.json
These changes provide structure, improve project maintainability, and make it easier for collaborators or others to understand and work with the project.
=> changes made in json

scripts/retriveprofile.js
issue #659 
**ignore the nav bar in the screenshot its just a screenshot problem**
=> added 2 more rows in each page

index.html, styles/styles.css
This is the second PR regarding footer having same functionality.
=> Updated the footer and removed extra space

index.html
FIXED ISSUE NO.#709
https://github.com/user-attachments/assets/86446dc8-c616-4f26-a338-5548cac67fbc
=> FIXED THE ISSUE

pages/githubbadge.html
=> fixed galaxy brain badge (how to get)

pages/githubbadge.html
=> fix pro badge

index.html, scripts/profileModal.js, styles/modal.css
This is the second pull request created with the same functionality of the popup modal.
https://github.com/user-attachments/assets/f97c1eac-ef53-4b77-83f9-0820f772919d
=> Added profile modal popup

index.html, login.css, login.html, login.js
changes made
issue #727
https://github.com/user-attachments/assets/b0501529-0cdf-49b0-a430-9b75223fe9b9
fixed it
=> ADDED THE DARK MODE FEATURE FOR MOBILE SCREENS

index.html, login.css, login.html, login.js
issue  #708
https://github.com/user-attachments/assets/fd49a4ba-b4d5-42ee-b21c-42280d15f19c
FIxed this
=>  insertion of hide password option deleted the login sign up switch

pages/compare.html, scripts/compare.js, styles/compare.css
-i have added profile avatar in compare page 
-the profile are being fetched from github-api
https://github.com/user-attachments/assets/1e919adc-115b-48a9-a8ec-571d8dc735fe
=> Added in avatar in compare page

index.html, pages/githubbadge.html, styles/hamburger.css, styles/styles.css
Closes #673 
fixed hamburger icon 
fixed searchbar icon
made navmenus box fixed
=> fixed navbar issue in mobileView

login.css, login.html, login.js
issue #738 fixed
- Realigned the locker icon in the password field to ensure proper positioning and consistency across the UI.
- Enhanced the locker icon functionality by making it toggle password visibility, similar to the eye icon. This will provide users with the ability to easily show or hide their password for better usability.
https://github.com/user-attachments/assets/e8a72c5d-185a-4a2e-b63b-95793cd80fe8
=> Fix locker icon misalignment and enhance password visibility toggle feature

pages/githubbadge.html
=> fixed YOLO issue #701

index.html, scripts/ScrollToTop.js, styles/styles.css
I have added the progress bar
https://github.com/user-attachments/assets/f2eeb5c3-3dd5-4fdc-8f43-38b1e1e458e7
Completed #748
=> Addition of Progress Bar | Issue #748

scripts/dark-mode.js, scripts/retriveprofile.js
I have made the following changes:-
1. Modal Option's Visibility in Dark Mode.
2. Modal Auto closing when clicking outside the modal.
Review the Video for references to the above-mentioned fixes.
https://github.com/user-attachments/assets/9c52e306-0183-4ef0-a4d3-9ffc966f9415
Completed #749
=> Fixes In Modal : Visibility and Modal Closing on Outside Click | Issue #749

pages/saved-blogs.html
Fixes #763: 
1. Redirect Bug fixed , Now Clicking on logo is redirected to ../index.html page.
2. Added a Button to go back to All Blogs Page. 
Please check the working in the video attached @sanjay-kv.
https://github.com/user-attachments/assets/76f571ec-c1ba-43b7-9393-d0ee88719c33
=> Fixes #763: Bug Fixed and Added Back to Blogs Button

styles/events.css
Issue Number: #718 
Event Page was not responsive in small screens.
It is fixed.
Before:
[recording.webm](https://github.com/user-attachments/assets/e72eb3e0-8c63-4200-8eb5-ea5a99a7189b)
After:
[After.webm](https://github.com/user-attachments/assets/11d1d6ad-27ae-4ac0-8d9e-88cf04051922)
=> adjusted responsiveness

styles/blog.css
popup overflow issue solved
issue no #780 
https://github.com/user-attachments/assets/9f66e2a1-f5cf-4120-bf57-e520fc24277c
=> popup overflow issue solved

index.html, pages/events.html, scripts/ScrollToTop.js
issue no - #782 
- resolved the scroll issue of navitem on learn and event page
=> Consistent scroll issue on all pages resolved

scripts/retriveprofile.js
It seemed to be a small issue, but it took my whole day 😥,
Well Fixes #785 
https://github.com/user-attachments/assets/31f09aa7-065a-4339-8c94-81e6718fc212
=> Fixes the Likes Functionality | Issue #785

styles/styles.css
This pull request addresses an alignment issue with the dark and light theme toggle buttons in the user interface. The buttons have been adjusted to be centered properly within their designated area, enhancing the overall visual consistency of the application.
Changes Made:
Adjusted CSS styles for the toggle buttons.
Ensured that the buttons are responsive and maintain alignment across different screen sizes.
=> Fix: Dark and Light Theme Button Misalignment

index.html, styles/styles.css
the icons are on top of everything even if the screen is smaller 
ISSUE #787
=> FIXED THE SIDE ICON ISSUE

pages/saved-blogs.html
issue no - #779 
- fixed the theme issue of saved blog page
https://github.com/user-attachments/assets/6c9d0612-ae3b-4aad-8dcb-414e2b9f3345
=> Theme issue of saved blog page

pages/help.html
Fixed #722 
Contact form is successfully added and functionality implemented.
=> Added Contact Form

index.html, login.html, pages/blog.html, pages/compare.html, pages/events.html, pages/githubbadge.html
ADDED A GOOD TRANSLATOR BUTTON ISSUE #815 
https://github.com/user-attachments/assets/04451317-1bd5-440c-a3fe-dcc218f9a939
=> ADDED THE TRANSLATOR FUNCTION

styles/speech.css
Completed #811 
https://github.com/user-attachments/assets/de535cfe-9c1e-4e1c-8928-ac283d7df4c4
=> Microphone Fixes | Issue #811

pages/blog.html, styles/blog.css
Fixed :-
1. Alignment Issue TopMate Banner.
2. Theme Mismatch in Dark Mode.
3. Topmate Link Hover effect missing.
4. Learn Section's Links are not Visible in Dark Mode.
https://github.com/user-attachments/assets/c66bb904-efac-4e9f-827b-461e273b9259
Completed #812
=> Fix TopMate Banner Theme, Alignment and Also Learn Section Links Theme Visibility Issue | Issue #812

pages/events.html
- added the scroll to top button on events page
https://github.com/user-attachments/assets/b16c03e1-8711-430e-82c8-ce4f8f014ce0
=> Scroll to top added on events page

styles/compare.css
Completed #813 
https://github.com/user-attachments/assets/4a823ece-6b01-48c4-99d6-2b5f19e92661
=> Added Frame to Contributor's Images | Added Undragability | Issue #813

styles/styles.css
fixes #827
Before :
- the footer was inconsistent with other footers
After :
- improved the logo size 
- added few hover effects in the headings n links
https://github.com/user-attachments/assets/36a5dc53-4549-4b5b-965c-c47ed066061f
=> footer aligned

scripts/retriveprofile.js
This PR closes issue #854 as mentioned earlier in issue #756.
=> [fix] change the UnLiked text

index.html, scripts/dark-mode.js, styles/styles.css
This PR closes issue #756, making the toggle button that toggles dark mode actually animate on Mobile like it animates on Desktop. Ultimately making this website responsive, having the same behaviour for Mobile and Desktop.
=> [fix] toggle button change theme for mobile

pages/blog.html, pages/compare.html, pages/events.html, pages/githubbadge.html, styles/blog.css, styles/compare.css, styles/events.css
https://github.com/user-attachments/assets/f5245943-01e5-4f9b-b56b-9e79ef1f13c4
Completed #829
=> Added B2Ts in Events Page | Progress Bar in Badges, Learn, Events and Compare Page | Issue #829

dashboard.css, login.css, styles/blog.css, styles/compare.css, styles/construction.css, styles/events.css, styles/explore.css, styles/githubbadge.css, styles/hamburger.css, styles/help.css, styles/modal.css, styles/pagination.css, styles/speech.css, styles/styles.css
=> CHANGED THE FONTS

index.html
Fixes: #892 892
Title:
[Fix]: Mic Button Visibility Bug on Hover Near Search Button
Description:
This pull request addresses the issue where the microphone button becomes visible when hovering near the search button. The bug was caused by unintended hover interactions affecting adjacent elements.
https://github.com/user-attachments/assets/649da681-03e2-467b-88e0-9e11dee16190
=> fixes:#Search_bug

pages/exploremore.html, styles/explore.css
https://github.com/user-attachments/assets/fd9a3346-9e87-46f3-a88a-091d9c97591a
#830 completed
=> Redesigning of COC Page

pages/compare.html, scripts/compare.js, styles/compare.css
**Added a loader in compare page which fixes issue:#838**
The submit button will turn to a loader until the API fetches data, to make sure that the user doesn't get the intuition of the website being lagged or hanged!!
=> fix: Added a loader || Issue: #838

README.md
Issue: #933 
Added https://github.com/Tusharb331 profile to readme.md
=> Add profile Tusharb331

tool.html
=> ADD TOOL PAGE

styles/styles.css
This pull request addresses the navbar content alignment and spacing issue reported in [Issue #875](https://github.com/recodehive/awesome-github-profiles/issues/875#event-14690356159). The following changes were made:
Centered Navbar Content: Adjusted the alignment of the navbar content to ensure it is perfectly centered, providing a balanced look across all screen sizes.
Reduced Spacing Between Logo and Brand Name: Modified the spacing between the logo and the brand name for a more cohesive appearance and improved visual harmony.
=> Fix: Navbar Alignment and Spacing (#875)

index.html
Fixes #911:
@sanjay-kv , I have changed the icons as per your suggestion. 
Also, Changed the redirect link of fb icon.
=> FIxes #911:  updated Social media icons 

.github/workflows/autocomment-issue-raise.yml
added the bot for auto commenting ISSUE #906
=> autocomment-issue-raise.yml   added 

index.html, styles/blog.css, styles/compare.css, styles/construction.css, styles/events.css, styles/explore.css, styles/githubbadge.css, styles/hamburger.css, styles/help.css, styles/modal.css, styles/pagination.css, styles/speech.css, styles/styles.css
issue number #570 
Changed/Altered the alignment body of the main page
All changes
➡️--> Header 
**In this also changed the logo's alignment
➡️-->Footer
⭐***Additionally , I have corrected the error of the side social media icons
• before
• after
=> Alignment Issue Of Body And Footer

index.html, pages/exploremore.html, styles/styles.css
I have added a hyperlink to the explore page thus now it is in working condition.
https://github.com/user-attachments/assets/a85bf6aa-f711-491c-9f54-03f7b2952203
This PR closes ISSUE #920 
@sanjay-kv @HimangshuSharma01
=> Explore page fix || ISSUE #920

styles/styles.css
This PR closes ISSUE #918. I have increased the logo size in the footer. 
@sanjay-kv @HimangshuSharma01
=> Increased the logo size || ISSUE #918

index.html, styles/styles.css
https://github.com/user-attachments/assets/88316746-146c-4631-b5f5-35b69153eeb6
I have added the link of the https://stream.recodehive.com/github to the footer of the text I 
This pr closes ISSUE #919 . I have added the hyperlink to the text
@sanjay-kv @HimangshuSharma01
=> Added hyper link on the footer text || ISSUE #919

index.html
This PR fixes the issue mentioned in Issue #908  where the Twitter icon was not rendering correctly. In addition to this, I've made improvements to the overall design and functionality of the social media icons.
Changes Made:
Fixed Twitter Icon: The Twitter icon is now rendering correctly and functions as expected.
Improved Alignment of Social Media Icons: Adjusted the layout to ensure all icons, including Facebook, LinkedIn, YouTube, and GitHub, are properly aligned and visible in the sidebar.
Before - 
After :
Video Proof:
https://github.com/user-attachments/assets/f1f5869f-1e5f-4195-a135-6c9f9bd10a89
I have attached a video showcasing the fixed icons and smooth animation for better clarity. You can view the changes here: 
These changes ensure that all social media icons are displayed …
=> Fix: Twitter Icon Not Working #908

progressbarvisibility.css, searchsuggestions.html, toolsforsmallerscreen.css
i enhanced three features as a part of the hacktoberfest
1. the progress bar visibility lacked css enhanced it
2. enhanced it for usage in small screens such as mobilephones and tablets
3.added search suggestions feature as html for user convenience
=> enhanced features

styles/styles.css
#971 
https://github.com/user-attachments/assets/9125ea0b-b152-4120-9764-869062ffb851
=> fixed the description

index.html, scripts/retriveprofile.js, styles/pagination.css
This is output of my changes..
=> add enhance/button-style-improve branch

index.html
=> added the link to code of conduct

.vscode/settings.json, pages/compare.html, scripts/compare.js, styles/compare.css
=> Added Stars and Github url to compare page

pages/githubbadge.html
=> Achievement Page update #2

styles/speech.css
Changed mic color to white in dark mode making it visible
Solved the issue #979
=> Changed mic color to white in dark mode

styles/styles.css
Changed footer text color in dark mode
Now text is visible easily.
Solved issue #980
=> Updated Footer text in Dark mode

pages/blog.html, scripts/blog.js
=> Add search bar to Blog Page

index.html, pages/faq.html, styles/faq.css
FAQ's SECTION 👍🏻 DONE 
https://github.com/user-attachments/assets/6654b74c-d5ce-47d2-9591-39ef56ef11e8
=> ADDED FAQ's SECTION

404.html
Added an Error:404 page just in case if any page is unable to load
=> Added Error:404 Page

pages/compare.html, scripts/compare.js, styles/compare.css
Fixes #921 
I have Added a feature to search for a user throughout the github as you requested @sanjay-kv . As I have shown the demo in #921 . 
Thank you for the opportunity @sanjay-kv . 
Ps: I would Like to work on more features / bugs , feel free to assign me.
=> Added a feature to search through github

scripts/retriveprofile.js, styles/styles.css
fixes #982 
@sanjay-kv Added social sharing option to all profiles.
Thankyou for the opportunity
screenshot:
https://github.com/user-attachments/assets/8f866c6c-e3ce-47a3-baab-4c213a18d52e
=> added social sharing option to profiles

login.html
I have implemented the required changes.
pls review the pull request.
=> Minimum password issue #1053 fixed

index.html
The logo in footer button now redirects to the top of the page.
Uploading Screen Recording 2024-10-24 115838.mp4…
=> FIXED : BUG: Footer logo not functional #1048

login.js
Fixes issue #1051
Before:-
After:-
For e-mail:-
For successful login:-
I have successfully added e-mail and user name validation.
Thanks @sanjay-kv
=> Added validation for username and e-mail

login.html, pages/compare.html, styles/styles.css
The nav icon in register & login page  and in compare page was not visible so i added link so they can be visible and font size in footer was small which i adjusted for readability.
Fixes the issue #1118
=> I added favicon and increase text size in footer

pages/githubbadge.html, scripts/dark-mode.js
https://github.com/user-attachments/assets/87be6ae0-2d37-4275-a3af-afdcb39ea75c
Fixed the issue #808
And ISSUE #567
https://github.com/user-attachments/assets/8617c46c-ab67-4f73-a38a-fb885bd64dc8
=> Fixed the bug and theme mode 

styles/styles.css
This pull request addresses issue [#1112](https://github.com/recodehive/awesome-github-profiles/issues/1112) by improving the user experience of the voice search feature. Currently, the microphone icon lacks a smooth transition effect when hovered over.
Changes Made:
- Added CSS transitions for hover state on the microphone icon.
- Adjusted opacity and scale for a more dynamic effect.
=> Enhance Microphone Hover Effect for Voice Search (#1112)

index.html
Closes Issue #571 
@sanjay-kv   @HimangshuSharma01  ,
I have added the Chatbot. Kindly check it out and please give level 3 it will be an honor
@HimangshuSharma01 ,
Thank You Sir for all the guidance and making this contribution possible. It really helped a lot.
https://github.com/user-attachments/assets/ca563d35-9583-4ae7-babe-fcdd48f8d122
=> Added a chatbot

index.html
fixes the problem in visibility of Twitter icon
Fixes #1057
=> Enabled the visibility of Twitter-icon

index.html, pages/stats.html
fix: #1072 
@sanjay-kv as you asked me to make it when user logs in then user stats should be visible, for now our login is not working i tried collecting it and saving it to the local storage , but that also was buggy so i implemented it this way for now....
=> Add Github stats page for personalised user experience 

pages/blog.html, pages/compare.html, pages/events.html, pages/exploremore.html, pages/githubbadge.html, pages/help.html, pages/saved-blogs.html
linked faq section to all pages at footer and made it consistent 
solved issue #1005 
like this:
=> linked faq section to all pages at footer and made it consistent 

pages/help.html
Changed color of labels to improve visibility
=> Changed color of labels to improve visibility 

pages/githubbadge.html
I added an info icon to enhance the user interface. As I'm new to the open-source, I’m very excited about it! Although it’s a minor contribution, it marks the beginning of my journey in contributing to the open-source community. I’d be grateful if you could review and merge it. Thank you for the opportunity, and I look forward to learning and contributing more!
Before: 
After:
=> Added "info icon"

index.html
=> Added visitor count to this web page

scripts/retriveprofile.js
https://github.com/user-attachments/assets/eb73add5-a74a-45c1-bf55-da6fa5dafff7
I improved the whole Js Please add level 2  
issue #1097
=> fixed the search bar and next button

CONTRIBUTING.md
I've made some enhancements to the project structure, including a dedicated section for project organization, a detailed pull request process, and clearer guidelines for issue reporting. I hope you find these changes beneficial.
Could you please add the labels "gesso-ext" and "hacktoberfest" and merge the pull request? Thank you!
=> fixes #1036

pages/compare.html, styles/compare.css
Before:
https://github.com/user-attachments/assets/37f7ec64-4665-45c1-8d44-003880661456
After:
https://github.com/user-attachments/assets/bc0f0910-11d2-4217-b0a2-835ffd68ede1
ISSUE #878   and   #653
=> Made Changes in the UI of Compare page

pages/compare.html
@sanjay-kv sir i have made some enhancements and also add a specific color palette for dark mode. please once review it and let me know if any further changes required 
solved issue #1143 
https://www.loom.com/share/0dec6eec636c48ff9a0b64a5de3a5775?sid=198e0151-5ea9-4eec-9e6a-0f07bdb7003c
=> improved the ui of compare contributor
